version: 2

env:
  - GO111MODULE=on

project_name: cfkvs
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/cfkvs/main.go
    binary: cfkvs
    ldflags:
      - -s
      - -w
      - -ldflags "-X 'github.com/michimani/cli.version={{.Version}}' -X 'github.com/michimani/cli.revision={{.ShortCommit}}'"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
release:
  prerelease: auto
brews:
  - repository:
      owner: michimani
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/michimani/cfkvs"
    description: "A simple command line tool for CloudFront Key Value Store"
    license: "MIT"
    test: |
      system "#{bin}/goreleaser -v"
