version: 2

env:
  - GO111MODULE=on

project_name: cfkvs
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/cfkvs/main.go
    binary: cfkvs
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
      - -X github.com/michimani/cli.version={{.Version}}
      - -X github.com/michimani/cli.revision={{.Commit}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - repository:
      owner: michimani
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/michimani/cfkvs"
    description: "A simple command line tool for CloudFront Key Value Store"
    license: "MIT"
    test: |
      system "#{bin}/goreleaser -v"
