name: onlytest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

env:
  GO_VERSION: "1.23"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go install

      - name: Test code
        run: go test -race -coverprofile="coverage.txt" -covermode=atomic github.com/michimani/cfkvs/... -shuffle=on -count=1

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
